# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20170626_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='line_item_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
