# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20170624_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='user',
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='customer',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
            preserve_default=False,
        ),
    ]
