# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Line',
            new_name='OrderLine',
        ),
    ]
