# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170626_1453'),
        ('orders', '0002_auto_20170626_1326'),
    ]

    operations = [
    ]
